language: node_js

node_js:
  - 0.10
  - 0.12

sudo: false

env:
  - NODE_ENV=test

before_script: ./tasks/travis_before_script.sh

script:
  - npm run coverage

after_script:
  - cat coverage/lcov.info | coveralls
